### ISSUE TITLE
Add option to provide labels for graph perimeter

### ISSUE THREAD

**Issue by cnsumner** [cnsumner/flutter-spider-chart#1]
While not necessary for a basic chart, perimeter labels would be nice to have.

**Comment by kostodo** [comment]
Any progress on this?

**Comment by cnsumner** [comment]
I've been very busy lately, but I hope to get back to this soon. It shouldn't be very difficult.

**Comment by cnsumner** [comment]
@kostodo working on this now, should have an update pushed soon
