### ISSUE TITLE
The getter 'length' was called on null

### ISSUE THREAD

**Issue by erpriliano** [cnsumner/flutter-spider-chart#4]
I tried to use the package like this :

```dart

  List<double> _data = [2, 3, 4, 5];
  List<Color> _colors = [Colors.red, Colors.green, Colors.brown, Colors.blue];

return Card(
   elevation: 4.0,
   clipBehavior: Clip.antiAlias,
   child: Container(
    color: Colors.yellow,
    width: 350,
    height: 350,
    padding: const EdgeInsets.all(5.0),
    child: SpiderChart(
     data: _data,
     colors: _colors,
     maxValue: 5.0,
   ),
 ),
);
```

and this happened

> I/flutter ( 2327): The following NoSuchMethodError was thrown during paint():
I/flutter ( 2327): The getter 'length' was called on null.
I/flutter ( 2327): Receiver: null
I/flutter ( 2327): Tried calling: length
I/flutter ( 2327): 
I/flutter ( 2327): Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
I/flutter ( 2327): be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
I/flutter ( 2327): 
I/flutter ( 2327): When the exception was thrown, this was the stack:
I/flutter ( 2327): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter ( 2327): #1      SpiderChartPainter.paint (package:spider_chart/spider_chart.dart:93:21)
I/flutter ( 2327): #2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:528:13)
I/flutter ( 2327): #3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
I/flutter ( 2327): #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #9      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 2327): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #13     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1989:11)
I/flutter ( 2327): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #23     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:548:11)
I/flutter ( 2327): #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #27     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:569:11)
I/flutter ( 2327): #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #31     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter ( 2327): #32     RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:1848:15)
I/flutter ( 2327): #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #35     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 2327): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #38     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter ( 2327): #41     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 2327): #42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter ( 2327): #43     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter ( 2327): #44     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter ( 2327): #45     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:937:29)
I/flutter ( 2327): #46     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:343:19)
I/flutter ( 2327): #47     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761:13)
I/flutter ( 2327): #48     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
I/flutter ( 2327): #49     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter ( 2327): #50     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter ( 2327): #51     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
I/flutter ( 2327): #53     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 2327): #54     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 2327): #55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 2327): (elided one frame from package dart:async-patch)
I/flutter ( 2327): 
I/flutter ( 2327): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#85437:
I/flutter ( 2327):   creator: CustomPaint ← LimitedBox ← SpiderChart ← Padding ← DecoratedBox ← ConstrainedBox ←
I/flutter ( 2327):     Container ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter ( 2327):     _InkFeatures-[GlobalKey#5d7cb ink renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯
I/flutter ( 2327):   parentData: <none> (can use size)
I/flutter ( 2327):   constraints: BoxConstraints(w=312.0, h=340.0)
I/flutter ( 2327):   size: Size(312.0, 340.0)
I/flutter ( 2327): This RenderObject has no descendants.
I/flutter ( 2327): ════════════════════════════════════════════════════════════════════════════════════════════════════

any idea why?

**Comment by andre-paraense** [comment]
I have been experiencing the exact same problem.

I/flutter (11275): Flutter error caught by Crashlytics plugin:
I/flutter (11275): The following exception was thrown during paint():
I/flutter (11275): NoSuchMethodError: The getter 'length' was called on null.
I/flutter (11275): Receiver: null
I/flutter (11275): Tried calling: length
I/flutter (11275): 
I/flutter (11275): debugCreator: CustomPaint ← LimitedBox ← SpiderChart ← ConstrainedBox ← Padding ← Container ← _PointerListener ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ← FeaturesChart ← ⋯
I/flutter (11275): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#c94e5
I/flutter (11275): RenderObject: RenderCustomPaint#c94e5
I/flutter (11275): 
I/flutter (11275): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (11275): #1      SpiderChartPainter.paint (package:spider_chart/spider_chart.dart:93:21)
I/flutter (11275): #2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:528:13)
I/flutter (11275): #3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
I/flutter (11275): #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter (11275): #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (11275): #6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11275): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter (11275): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (11275): #9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11275): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193:7)
I/flutter (11275): #11     PaintingContext.paintChild (package:flutter/src/rendering/

**Comment by andre-paraense** [comment]
I found the problem. The SpiderChart constructor is not marking the `labels` attribute as `@required`, but later on in the code it is using it to get the `length` and of course operating on a null pointer in cases when it is not passed.

Hence, a simple workaround is to pass labels as a list of empty strings for now, or even real labels for your data. @erpriliano, in your code above, it could be something like: 

```
List<double> _data = [2, 3, 4, 5];
List<Color> _colors = [Colors.red, Colors.green, Colors.brown, Colors.blue];
List<String> _labels = _data.map((data) => '').toList();

return Card(
   elevation: 4.0,
   clipBehavior: Clip.antiAlias,
   child: Container(
    color: Colors.yellow,
    width: 350,
    height: 350,
    padding: const EdgeInsets.all(5.0),
    child: SpiderChart(
     data: _data,
     colors: _colors,
     maxValue: 5.0,
     labels: _labels,
   ),
 ),
);
```
@cnsumner to fix this, I think you could either make labels `@required` or treat the case when it is null.

**Comment by cnsumner** [comment]
You are correct, the null case is meant to be handled, but isn't. My bad.

In the meantime, use the empty string lable workaround @andre-paraense posted above. I'll fix this is soon as I have time.

On a side note: if anyone feels like attempting a PR to fix this, feel free, since I may take a bit to get to it.

**Comment by cnsumner** [comment]
So it turns out I was clever and did actually intend to not set labels as required, however I made a typo later, checked whether `labels.length` was null instead of checking if `labels` was null 🤦‍♂️

**Comment by cnsumner** [comment]
@erpriliano I will have the fix pushed out shortly
